<script setup lang="ts">
/**
 * Legal notice.
 *
 * The position the game takes: real clubs appear under their real names,
 * because a football management game that renames them is describing a
 * different sport. Nothing else is real — every player, member of staff,
 * agent, owner and ground in the game is generated, and no crest, kit design
 * or likeness of any real person is used.
 */
import { APP_NAME, APP_VERSION } from '../../version'
</script>

<template>
  <div>
    <div class="card">
      <div class="card__body">
        <div class="bold" style="font-size: 1.1rem">{{ APP_NAME }}</div>
        <div class="small muted">Version {{ APP_VERSION }}</div>
      </div>
    </div>

    <div class="section-title">Club and competition names</div>
    <div class="card">
      <div class="card__body">
        <p class="small" style="margin: 0 0 10px">
          {{ APP_NAME }} lets you simulate a football club and the world it plays in.
          Third-party names are used only to identify the real clubs taking part in that
          simulation, and for no other purpose.
        </p>
        <p class="small" style="margin: 0 0 10px">
          No club, competition, organisation or individual endorses {{ APP_NAME }} or is
          associated with it, and no endorsement or association is claimed or implied.
        </p>
        <p class="small" style="margin: 0">
          All third-party trade marks are the property of their respective owners. No
          warranty or representation is made in respect of them.
        </p>
      </div>
    </div>

    <div class="section-title">Everything else is invented</div>
    <div class="card">
      <div class="card__body">
        <p class="small" style="margin: 0 0 10px">
          Every player, coach, scout, agent, owner, architect and journalist in this game is
          generated by the game itself. None is intended to represent any real person, living
          or dead, and any resemblance is coincidental.
        </p>
        <p class="small" style="margin: 0">
          Stadiums, crests, kits and colours are likewise generated or chosen by the game. No
          image, badge, kit design or likeness belonging to any third party is intentionally
          used, and any similarity to one is coincidental and implies no endorsement or
          association.
        </p>
      </div>
    </div>

    <div class="section-title">Your data</div>
    <div class="card">
      <div class="card__body">
        <p class="small" style="margin: 0">
          Saved games are stored on this device and nowhere else. Nothing you do in the game
          is transmitted anywhere, and no account is required to play it.
        </p>
      </div>
    </div>
  </div>
</template>
