import { chromium } from 'playwright'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
page.on('pageerror', e => console.log('PAGEERROR:', e.message))
await page.goto('http://127.0.0.1:4173/', { waitUntil: 'networkidle' })
await page.click('text=Start a new career')
await page.fill('#dof-name', 'Test')
await page.click('.segmented__item:has-text("Compact")')
await page.click('text=Create world')
await page.waitForSelector('text=Take a job', { timeout: 60000 })
await page.click('.btn:has-text("More detail") >> nth=0')
await page.click('.btn:has-text("Take the job at")')
await page.waitForSelector('.tabbar', { timeout: 30000 })
await page.waitForTimeout(1500)
const btns = await page.locator('.content button').allTextContents()
console.log('buttons in content:', JSON.stringify(btns.map(b=>b.trim().slice(0,40))))
for (const sel of ['.btn--primary:has-text("Advance week")', 'button.btn--primary', 'text=Advance week', '.btn:has-text("Advance week")']) {
  console.log(sel, '->', await page.locator(sel).count())
}
console.log('classes:', await page.locator('text=Advance week').first().getAttribute('class'))
await browser.close()
